### ISSUE TITLE
Throws error when using the click method on the document

### ISSUE THREAD

**Issue by imaustink** [bitovi/funcunit#206]
If you use `.click` like this `f.click(document)`, it throws the following error.
```
syn.js:173 Uncaught TypeError: Cannot read property 'jQuery' of undefined
    at Function.jquery (https://unpkg.com/syn@0.5.0/dist/global/syn.js:173:49)
    at Object.addOffset (https://unpkg.com/syn@0.5.0/dist/global/syn.js:326:30)
    at init._click (https://unpkg.com/syn@0.5.0/dist/global/syn.js:515:25)
    at new init (https://unpkg.com/syn@0.5.0/dist/global/syn.js:155:27)
    at syn (https://unpkg.com/syn@0.5.0/dist/global/syn.js:131:20)
    at Function.syn.(anonymous function) [as click] (https://unpkg.com/syn@0.5.0/dist/global/syn.js:578:24)
    at HTMLDocument.<anonymous> (https://fiddle.jshell.net/0xxjv2o0/1/show/:49:5)
    at fire (https://code.jquery.com/jquery-2.1.3.js:3094:30)
    at Object.fireWith [as resolveWith] (https://code.jquery.com/jquery-2.1.3.js:3206:7)
    at Function.ready (https://code.jquery.com/jquery-2.1.3.js:3412:13)
```
[JSfiddle](https://jsfiddle.net/0xxjv2o0/1/)

**Comment by chasenlehara** [comment]
That looks like an issue in Syn, is it not?

**Comment by justinbmeyer** [comment]
Try on the document.documentElement or document.body then.

**Comment by imaustink** [comment]
Issue moved to [bitovi/syn #140](https://github.com/bitovi/syn/issues/140) via [**ZenHub**](https://www.zenhub.com/)
