### ISSUE TITLE
Basic click does not work in IE

### ISSUE THREAD

**Issue by raviviswanathan** [bitovi/funcunit#69]
am running a basic funcunit test as below for the test.html.. which has only

``` html
<html><body><div>Test</div></body></html>
```

``` js
module('test', {
  setup: function() {
    F.open('test.html');
  }
});

//test to verify that head, body are not empty

test("Page render Test : Head, Body and Header message", function(){
 ok( F("body").size(), "There are elements in the Head"); //head is not empty 
 F('body').click();
});
```

This gives the below error

1.There are elements in the Head
2.Unspecified error.Source: /j/test/resources/jquery.js:6110

3.Could not click 'body'Source: at assertOK (/j/test/resources/funcunit.js:2720:4)
at Anonymous function (/j/test/resources/funcunit.js:4243:8)

**Comment by mickmcgrath13** [comment]
@alexisabril  We're using 1.11, now.  Can this be closed?
